# Generated by Django 5.0 on 2025-09-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_cer_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="data_processing",
            field=models.BooleanField(
                default=False,
                help_text="Consenso al trattamento dei dati personali",
                verbose_name="Trattamento Dati",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="data_processing_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e ora di lettura dell'accordo trattamento dati",
                null=True,
                verbose_name="Timestamp Trattamento Dati",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="privacy_policy",
            field=models.BooleanField(
                default=False,
                help_text="Consenso alla privacy policy",
                verbose_name="Privacy Policy",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="privacy_policy_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e ora di lettura della privacy policy",
                null=True,
                verbose_name="Timestamp Privacy Policy",
            ),
        ),
    ]
