# Generated by Django 5.0 on 2025-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_fix_model_test_mismatches"),
    ]

    operations = [
        migrations.AddField(
            model_name="cermembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
