# Generated by Django 5.0 on 2025-09-06 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_missing_timestamp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="cermembership",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
