# Generated by Django 5.0 on 2025-09-04 18:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BILL", "Bolletta Energia"),
                            ("SYSTEM_CERT", "Certificato Conformità Impianto"),
                            ("GSE_DOC", "Documentazione GSE"),
                            ("PANELS_PHOTO", "Foto Pannelli"),
                            ("INVERTER_PHOTO", "Foto Inverter"),
                            ("PANELS_LIST", "Elenco Seriali Pannelli"),
                            ("ID_DOC", "Documento Identità"),
                            ("GAUDI", "Attestazione Gaudì"),
                            ("OTHER", "Altro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo Documento",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("USER", "Caricato da Utente"),
                            ("SYSTEM", "Generato dal Sistema"),
                        ],
                        default="USER",
                        max_length=10,
                        verbose_name="Origine Documento",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Formati supportati: PDF, JPG, PNG. Dimensione massima: 10MB",
                        upload_to="documents/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Note opzionali sul documento",
                        verbose_name="Note",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Caricamento"
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "In attesa"),
                            ("PROCESSING", "In elaborazione"),
                            ("COMPLETED", "Completato"),
                            ("FAILED", "Fallito"),
                        ],
                        default="PENDING",
                        help_text="Stato dell'elaborazione del documento",
                        max_length=20,
                        null=True,
                        verbose_name="Stato Elaborazione",
                    ),
                ),
                (
                    "processing_errors",
                    models.TextField(
                        blank=True,
                        help_text="Eventuali errori durante l'elaborazione del documento",
                        null=True,
                        verbose_name="Errori Elaborazione",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e ora dell'elaborazione del documento",
                        null=True,
                        verbose_name="Data Elaborazione",
                    ),
                ),
                (
                    "gdpr_consent",
                    models.BooleanField(
                        default=False,
                        help_text="L'utente ha acconsentito al trattamento dei dati contenuti nel documento",
                        verbose_name="Consenso GDPR",
                    ),
                ),
                (
                    "retention_date",
                    models.DateField(
                        blank=True,
                        help_text="Data fino alla quale il documento deve essere conservato",
                        null=True,
                        verbose_name="Data di Conservazione",
                    ),
                ),
                (
                    "data_classification",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Pubblico"),
                            ("INTERNAL", "Interno"),
                            ("CONFIDENTIAL", "Confidenziale"),
                            ("PERSONAL", "Dati Personali"),
                        ],
                        default="INTERNAL",
                        help_text="Livello di riservatezza del documento",
                        max_length=20,
                        verbose_name="Classificazione Dati",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 checksum del file per verifica integrità",
                        max_length=64,
                    ),
                ),
                (
                    "encryption_status",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se il documento è stato crittografato",
                        verbose_name="Stato Crittografia",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e ora dell'ultimo accesso al documento",
                        null=True,
                        verbose_name="Ultimo Accesso",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Impianto associato al documento (opzionale)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_documents",
                        to="core.plant",
                        verbose_name="Impianto",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Caricato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documenti",
                "ordering": ["-uploaded_at"],
                "permissions": [
                    ("view_confidential", "Può visualizzare documenti confidenziali"),
                    ("view_personal_data", "Può visualizzare dati personali"),
                    ("extend_retention", "Può estendere il periodo di conservazione"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_timestamp", models.DateTimeField(auto_now_add=True)),
                ("access_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "accessed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accesso Documento",
                "verbose_name_plural": "Accessi Documenti",
                "ordering": ["-access_timestamp"],
            },
        ),
    ]
