name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
      - name: Install pip deps (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install -r CerCollettiva/requirements.txt
          pip install pre-commit
      - name: Run pre-commit (black/isort/ruff)
        run: |
          pre-commit run --all-files || true
      - name: Django check
        working-directory: CerCollettiva
        env:
          DJANGO_SETTINGS_MODULE: cercollettiva.settings.local
        run: |
          python manage.py check

